config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  get 'posts/index'
  resources :posts
  root 'posts#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/search', to: 'search#search', :as => 'search_page'
  
  resources :users, param: :username
  resources :favorite_posts, only: [:create, :destroy]
  resources :favorites

  resources :posts do
    resources :comments
  end
  resources :comments do
  resources :comments
end
  
  resources :posts do
    member do
      put "upvote", to: "posts#upvote"
      put "downvote", to: "posts#downvote"
    end
  end
  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
  resources :channels
  resources :channels do
    member do
      put "subscribe", to: "channels#subscribe"
      put "unsubscribe", to: "channels#unsubscribe"
    end
  end
  
  
  
  

  

  
  
end

app/models/channel.rb
class Channel < ActiveRecord::Base
    attachment :channel_image
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
     respond_to do |format|
      format.js {render layout: false} # Add this line to you respond_to block
    end
    def new
        @channel = Channel.new
    end
    def create
      @channel = Channel.new(channel_params)
      if @channel.save
       flash[:notice] = "Channel was successfully created"
       if !current_user.nil?
        user= User.find(current_user.id)
        sub_nums= user.subscriptions + @channel.id.to_s + ","
        user.subscriptions=sub_nums
        user.save!
       end
       redirect_to channel_path(@channel)
      else
       render 'new'
      end
    end
  def show
      @channel = Channel.find(params[:id])
  end
  def subscribe
        if current_user.nil?
            flash[:notice] = "You must be logged in to subscribe"
        else
            @channel = Channel.find(params[:id])
            user= User.find(current_user.id)
            sub_nums= user.subscriptions + @channel.id.to_s + ","
            user.subscriptions=sub_nums
            user.save!
            redirect_to channel_path(@channel)
        end
        
        
    end
    def unsubscribe
        if current_user.nil?
            flash[:notice] = "You must be logged in to unsubscribe"
        else
            @channel = Channel.find(params[:id])
            user= User.find(current_user.id)
            sub_nums= user.subscriptions
            user.subscriptions=sub_nums.remove(@channel.id.to_s + ",")
            user.save!
             redirect_to channel_path(@channel)
        end
        
        
    end
  
  
  
  
  private
  def channel_params
    params.require(:channel).permit(:channel_name, :channel_description, :channel_guidelines, :channel_image, :moderators)
  end
    
end

app/helpers/channels_helper.rb
module ChannelsHelper
    def check_subcription(id)
        if current_user.nil?
            return false
        elsif current_user.subscriptions.nil?
            return false
        elsif current_user.subscriptions.include? id.to_s+","
            return true
        else
            return false
        end
    end
end

app/views/channels/_subscribe.html.erb
<% @channel = Channel.find(params[:id]) %>

<% if !current_user.nil? && check_subcription(@channel.id) %>
    <%= link_to unsubscribe_channel_path(@channel.id), method: :put,remote: true do %>
    <div class="unsubscribe_button">&#8722;</div>
    <% end %>
<% elsif !current_user.nil? && !check_subcription(@channel.id) %>
    <%= link_to subscribe_channel_path(@channel.id), method: :put,remote: true do %>
    <div class="subscribe_button">&#43;</div>
    <% end %>
<% else %>

<% end %>

app/views/channels/index.html.erb
<% Channel.all.each do |channel| %>
<a href="<%= channel_path(channel.id)%>">
<div class="post_item masonry-brick">
<% if(!channel.channel_image.nil?) %>
<%= image_tag attachment_url(channel, :channel_image, format: "jpg"), :class => "channel_image_tiny" %>
<% end %>
<h2 style="display: inline-block;"><%= channel.channel_name %></h2>
</div>
</a>
<% end %>

app/views/channels/new.html.erb
<h1>Create a Channel</h1>
<center>
 <div class="new_post_form">
<%= form_for @channel do |f| %>
 <p>
  <%= f.label :channel_name %><br>
  <%= f.text_field :channel_name %>
 </p>
 <p>
  <%= f.label :channel_description %><br>
  <%= f.text_area :channel_description %>
 </p>
 <p>
  <%= f.label :channel_guidelines %><br>
  <%= f.text_area :channel_guidelines %>
 </p>
 <p id="photo_gif">
  <%= f.label "Channel Image" %><br>
  <%= f.attachment_field :channel_image %>
 </p>
  <%= f.hidden_field :moderators, :value => current_user.id.to_s+"," %>
 <p>
  <%= f.submit %>
 </p>
<% end %>
</div>
</center>

app/views/channels/show.html.erb
<% if(!@channel.channel_image.nil?) %>
<%= image_tag attachment_url(@channel, :channel_image, format: "jpg"), :class => "channel_image" %>
<% end %>
<div class="channel_info">
<h1 style="display: inline-block;">#<%= @channel.channel_name %></h1>
<div id="subscription_button"><%= render 'channels/subscribe', :@channel => @channel %></div>
<h4>Channel Description</h4>
<h5><%= @channel.channel_description %></h5>
<h4>Channel Rules</h4>
<h5><%= @channel.channel_guidelines %></h5>
</div>
<div class="masonry">
  <% Post.where(:channel_id => @channel.id).each do |post| %>
  <div class="post_item masonry-brick">
  <a href="<%= user_path(get_username(post.user_id))%>">@<%= get_username(post.user_id)%></a><br>
  #<%= get_channel_name(post.channel_id) %>
 <a href=<%= post_path(post) %>>
  <h2><%= post.title %></h2> </a>
  <center><h3 class="post_content"><%= post.content %></h3></center>
  <% if(post.link== "" || post.link.nil?) %>
 <center><%= image_tag attachment_url(post, :media_content, format: "jpg"), :class => "post_image" %></center>
 <% else %>
 <center><iframe width="700px" height="400px" src="<%= post.link %>" frameborder="0" allowfullscreen></iframe></center>
<% end %>
  <div class="comment-count">
                <span class="tag is-rounded"><%= post.comments.count %> comments</span>
            </div>
  <%= render 'posts/votes', :@post => post %>
 </div>
  <% end %>
  </div>

app/views/channels/subscribe.js.erb
$("#subscription_button").html("<%= escape_javascript(render partial: 'channels/subscribe', locals: { channel: @channel } ) %>");