config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  get 'posts/index'
  resources :posts
  root 'posts#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/search', to: 'search#search', :as => 'search_page'
  
  resources :users, param: :username
  resources :favorite_posts, only: [:create, :destroy]
  resources :favorites

  resources :posts do
    resources :comments
  end
  resources :comments do
  resources :comments
end
  
  resources :posts do
    member do
      put "upvote", to: "posts#upvote"
      put "downvote", to: "posts#downvote"
    end
  end
  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
  resources :channels
  resources :channels do
    member do
      put "subscribe", to: "channels#subscribe"
      put "unsubscribe", to: "channels#unsubscribe"
    end
  end
  
  
  
  

  

  
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    validates :body, length: { minimum: 2 }
    validates :body, length: { maximum: 500 }
    validates :user_id, presence: true
    belongs_to :user
    belongs_to :post
    belongs_to :comment
    belongs_to :commentable, :polymorphic => true
    has_many :comments, :as => :commentable
    acts_as_votable
    
    def score
        self.get_upvotes.size - self.get_downvotes.size
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to do |format|
      format.js {render layout: false} # Add this line to you respond_to block
    end
before_action :find_commentable

    def new
      @comment = Comment.new
    end

    def create
      @comment = @commentable.comments.new comment_params

      if @comment.save
        redirect_to :back, notice: 'Your comment was successfully posted!'
      else
        redirect_to :back, notice: "Your comment couldn't be posted!"
      end
    end
    def destroy
      @post = Post.find(params[:post_id])
      @comment = Comment.find(params[:id])
      @comment.destroy
    
      redirect_to post_path(@post)
    end
    def upvote
      @comment = Comment.find(params[:id])
      @comment.upvote_by current_user
     render :template => "comments/votes"
    end
    def downvote
      @comment = Comment.find(params[:id])
      @comment.downvote_by current_user
        render :template => "comments/votes"    end
    private

    def comment_params
      params.require(:comment).permit(:body, :user_id)
    end

    def find_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Post.find_by_id(params[:post_id]) if params[:post_id]
    end
    

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment-<%= comment.id %>">
  <a href="<%= user_path(get_username(comment.user_id))%>">@<%= get_username(comment.user_id)%></a><br>
  <%= comment.body %><br>
  <small><%= time_ago_in_words(comment.created_at) %> ago</small>
  <% if logged_in? %>
  <span class="reply_prompt" id="reply_prompt_<%= comment.id %>" onclick="showReply(<%= comment.id %>)">Reply</span>
  <div class="reply" id="comment_reply_<%= comment.id %>">
  <%= form_for [comment, Comment.new] do |f| %>
      <%= f.text_area :body, placeholder: "Add a Reply" %><br/>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.submit "Reply"  %>
      <% end %>
  </div>
  <% end %>
  <% if check_permissions(comment.user_id) %>
     <%= link_to 'Delete', 
                             post_comment_path(@post, comment), 
                             method: :delete,
                             data: { confirm: 'Are you sure you want to delete this comment?' } %>   
    <% end %>
  </post>
  <%= render 'comments/votes', :@comment => comment %>
</div>
  <ul>
      <%= render partial: 'comments/comment', collection: comment.comments.order('cast(created_at as date) desc, cached_votes_up desc') %>
  </ul>

app/views/comments/_form.html.erb
<%= form_for [@comment, Comment.new] do |f| %>
      <%= f.text_area :body, placeholder: "Add a Reply" %><br/>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.submit "Reply"  %>
      <% end %>

app/views/comments/_votes.html.erb
<div id="<%= get_votes_class(@comment.id) %>" class="votes">
 <%= link_to "▲", upvote_comment_path(@comment.id), method: :put,remote: true, class: "voter"%>  
 <%= @comment.score %>
  <%= link_to "▼", downvote_comment_path(@comment.id), method: :put,remote: true, class: "voter" %>  
</div>

app/views/comments/new.html.erb
<%= form_for [@commentable, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h2>Please correct the following errors.</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body, rows: 8 %>
     <%= f.hidden_field :user_id, :value => current_user.id %>
     <%= f.hidden_field :post_id, :value =>  params[:post_id]  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/votes.js.erb
$("#<%= escape_javascript(get_votes_class(@comment.id)) %>").html("<%= escape_javascript(render partial: 'comments/votes', locals: { comment: @comment } ) %>");