config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  get 'posts/index'
  resources :posts
  root 'posts#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/search', to: 'search#search', :as => 'search_page'
  
  resources :users, param: :username
  resources :favorite_posts, only: [:create, :destroy]
  resources :favorites

  resources :posts do
    resources :comments
  end
  resources :comments do
  resources :comments
end
  
  resources :posts do
    member do
      put "upvote", to: "posts#upvote"
      put "downvote", to: "posts#downvote"
    end
  end
  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
  resources :channels
  resources :channels do
    member do
      put "subscribe", to: "channels#subscribe"
      put "unsubscribe", to: "channels#unsubscribe"
    end
  end
  
  
  
  

  

  
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  attachment :media_content
  # searchable do 
  #   text :title, :content
  # end 

  validates :title, length: { minimum: 2 }
  validates :title, length: { maximum: 200 }
    has_many :favorites, as: :favorited
    has_many :comments, as: :commentable
    acts_as_votable
    def score
        self.get_upvotes.size - self.get_downvotes.size
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    respond_to do |format|
      format.js {render layout: false} # Add this line to you respond_to block
    end
    def index
        if current_user.nil? || current_user.subscriptions.nil?
            @posts = Post.all
            
            # @posts = Post.order('created_at DESC')
            @posts=Post.order('cached_votes_score desc, cast(created_at as date) desc')
        else
            subs=current_user.subscriptions.split(',')
            @posts = Post.where(channel_id: subs).order('cached_votes_score desc, cast(created_at as date) desc')
        end

    end
    def new
        @post = Post.new
    end
    def create
      @post = Post.new(post_params)
      if @post.save
       flash[:notice] = "Post was successfully created"
       redirect_to post_path(@post)
      else
       render 'new'
      end
    end
    
    #def bookmark
    #    @post = Post.find(params[:id])
    #    @post = Post.bookmark_by current_user
    #    flash[:notice] = "Added to bookmarks!"
    #end
    
    def edit
      @post = Post.find(params[:id])
    end
    def update
      @post = Post.find(params[:id])
      if @post.update(post_params)
       flash[:notice] = "Post was updated"
       redirect_to post_path(@post)
      else
       flash[:notice] = "Post was not updated"
       render 'edit'
      end
    end
    def show
        @post = Post.find(params[:id])
        # @comments = @commentable.comments
        @comment = Comment.new
    end
    def upvote
      @post = Post.find(params[:id])
      @post.upvote_by current_user
     render :template => "posts/votes"
    end
    def downvote
      @post = Post.find(params[:id])
      @post.downvote_by current_user
        render :template => "posts/votes"    end
    def destroy
      @post = Post.find(params[:id])
      @post.destroy
    
      redirect_to root_path
    end
    private
    def post_params
        params.require(:post).permit(:channel_id, :title, :content, :link, :user_id, :media_content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_showPost.html.erb
<div class="masonry">
 <% post=Post.find(post_id) %>
 <div class="post_item">
 <a href=<%= post_path(post) %>>
  <h2><%= post.title %></h2> </a>
  <h3><%= post.content %></h3>
  <img class="photo_post_tile" src="<%= post.link %>"></img>
  <div class="comment-count">
                <span class="tag is-rounded"><%= post.comments.count %> comments</span>
            </div>
  <div class="votes">▲ <%= post.votes %> ▼</div>
 </div>

 </div>
 

app/views/posts/_votes.html.erb
<div id="<%= get_votes_class(@post.id) %>" class="votes">
 <%= link_to "▲", upvote_post_path(@post.id), method: :put,remote: true, class: "voter"%>  
 <%= @post.score %>
  <%= link_to "▼", downvote_post_path(@post.id), method: :put,remote: true, class: "voter" %>  
</div>

app/views/posts/edit.html.erb
<h1>Edit Article</h1>
<% if @post.errors.any? %>
 <h2>The following errors prevented the post from saving:</h2>
 <ul>
 <% @post.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>
<%= form_for @post do |f| %>
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
 </p>
 <p>
  <%= f.label :content %><br>
  <%= f.text_area :content %>
 </p>
 <p>Media Type</p>
 <select id="media_type" onchange=showMediaInput()>
 <option value="photo">Photo/GIF</option>
 <option value="video">Video Link</option>
 </select>
 <p id="photo_gif">
  <%= f.label "Media" %><br>
  <%= f.attachment_field :media_content %>
 </p>
 <p id="video_link" style="display: none;">
  <%= f.label "Video Link" %><br>
  <%= f.text_field :link %>
 </p>
 <%= f.hidden_field :user_id, :value => current_user.id %>
 <p>
  <%= f.submit %>
 </p>
<% end %>
<%= link_to 'Delete', @post, :method => :delete, :data => {:confirm => 'Are you sure?'} %>

app/views/posts/index.html.erb
<div class="masonry">
 <% @posts.each do |post| %>
 <div class="post_item masonry-brick">
  <a href="<%= user_path(get_username(post.user_id))%>">@<%= get_username(post.user_id)%></a><br>
  <a href="<%= channel_path(post.channel_id)%>">#<%= get_channel_name(post.channel_id) %></a>
 <a href=<%= post_path(post) %>>
  <h2><%= post.title %></h2> 
  <center><h3 class="post_content"><%= post.content %></h3></center>
  <% if(post.link== "" || post.link.nil?) %>
 <center><%= image_tag attachment_url(post, :media_content, format: "jpg"), :class => "post_image" %></center>
 <% else %>
 <center><iframe width="700px" height="400px" src="<%= post.link %>" frameborder="0" allowfullscreen></iframe></center>
<% end %>
 </a>
  <a href=<%= post_path(post) %>><div class="comment-count">
                <span class="tag is-rounded"><%= post.comments.count %> comments</span>
            </div></a>
  <%= render 'posts/votes', :@post => post %>
  
 </div>

 <% end %>
 </div>

app/views/posts/new.html.erb
<h1>Create a Post</h1>
<center>
 <div class="new_post_form">
<%= form_for @post do |f| %>
 <p>
  <%= f.label "Channel" %><br>
  <%= f.collection_select :channel_id, Channel.all, :id, :channel_name %>
 </p>
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
 </p>
 <p>
  <%= f.label :content %><br>
  <%= f.text_area :content %>
 </p>
 <p>Media Type</p>
 <select id="media_type" onchange=showMediaInput()>
 <option value="photo">Photo/GIF</option>
 <option value="video">Video Link</option>
 </select>
 <p id="photo_gif">
  <%= f.label "Media" %><br>
  <%= f.attachment_field :media_content %>
 </p>
 <p id="video_link" style="display: none;">
  <%= f.label "Video Link" %><br>
  <%= f.text_field :link %>
 </p>
  <%= f.hidden_field :user_id, :value => current_user.id %>
 <p>
  <%= f.submit %>
 </p>
<% end %>
</div>
</center>

app/views/posts/show.html.erb
<div class="post_page">
<div class="main_post_content">
<div class="main_post_item">
<%= link_to 'Back to Home', root_path %>
<span class="edit">
<% if !current_user.nil? && check_time_permissions(@post.user_id, @post.id) %>
<%= link_to 'Edit', edit_post_path(@post) %><br>
<% elsif !current_user.nil? && check_permissions(@post.user_id) %>
<%= link_to 'Delete', @post, :method => :delete, :data => {:confirm => 'Are you sure?'} %><br>
<% end %>
<%- unless current_user.nil? || current_user.favorites.exists?(favorited_id: @post.id) -%>
  <%= link_to 'Add to favorites', favorites_path(post_id: @post), method: :post %>
  <%- else if !current_user.nil? -%>
  <%= link_to 'Remove from favorites', favorite_path(@post), method: :delete %> 
  <% else %>
  <%- end -%><%- end -%>
</span>
<br>
<a href="<%= user_path(get_username(@post.user_id))%>">@<%= get_username(@post.user_id)%></a>
<br><a href="<%= channel_path(@post.channel_id)%>">#<%= get_channel_name(@post.channel_id) %><br></a>
<h1><%= @post.title %></h1>
<h3><%= @post.content %></h3>
<% if(@post.link.nil? || @post.link == "") %>
<center><%= image_tag attachment_url(@post, :media_content, format: "jpg"), :class => "post_image" %></center>
<% else %>
<center><iframe width="700px" height="400px" src="<%= @post.link %>" frameborder="0" allowfullscreen></iframe></center>
<% end %>
<small class="comment-count">Posted <%= time_ago_in_words(@post.created_at) %> ago</small>
<%= render 'posts/votes', :@post => @post %>

</div>

</div>
<div class="comments">
<center><h3> <%= @post.comments.count %> Comments</center>

        

          <%= render(partial: 'comments/comment', collection: @post.comments.order('cast(created_at as date) desc, cached_votes_up desc')) %>

        <div class="comment-form">
            <hr />
            <h3 class="subtitle is-3">Leave a reply</h3>
            <% if logged_in? %>
            <div class="comment_input">
              <%= form_for [@post, Comment.new] do |f| %>
                <%= f.text_area(:body, size: '50x10', class: "comment_input", id: "comment_input", placeholder: "Add a comment") %><br/>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.submit "Add Comment" %>
                <% end %>
            </div>
            <% else %>
            <p>You must be logged in to comment on posts.</p>
            <% end %>
        </div>


</div>
</div>

app/views/posts/votes.js.erb
$("#<%= escape_javascript(get_votes_class(@post.id)) %>").html("<%= escape_javascript(render partial: 'posts/votes', locals: { post: @post } ) %>");